### ISSUE TITLE
Could you put exhaustion into it's own branch?

### ISSUE THREAD

**Issue by adam-winchell** [slafniy/DedTunedProject#24]
I created the mod https://mod.io/g/baldursgate3/m/extraordinaryactions which is based on some content I wrote for dnd 5e which originally uses exhaustion. I wrote my mod with a different mechanic because I couldn't figure out how to do exhaustion in bg3. I would appreciate to use what you wrote as part of my mod.

**Comment by slafniy** [comment]
I can try when I have time, it shouldn't be hard :)

**Comment by slafniy** [comment]
I created a separate branch and removed all files except mod meta files and Exhaustion

Exhaustion is literally one file + localization:
https://github.com/slafniy/DedTunedProject/blob/d0ce2cad81238107c70d17819fc36e6e2188e3b6/Data/Public/DedTuned_de9f3db5-7ca9-a872-75d4-3cc4a09a90cd/Stats/Generated/Data/DT_Exhaustion.txt
https://github.com/slafniy/DedTunedProject/blob/d0ce2cad81238107c70d17819fc36e6e2188e3b6/Data/Mods/DedTuned_de9f3db5-7ca9-a872-75d4-3cc4a09a90cd/Localization/English/EN_Exhaustion.loca.xml

Please note I replaced my custom icons with basic ones to reduce mod size.
I briefly checked this branch and it seems working.
